### ISSUE TITLE
Use as Input Field Date Picker

### ISSUE THREAD

**Issue by owwas-nqb** [hanafnafs/angular-hijri-gregorian-datepicker#4]
Can it be used as an input field Date Picker Collapse and Expendable ?.

![image](https://github.com/user-attachments/assets/6f82c72b-4558-4c8a-853a-86f2e01cc7b6)

**Comment by hanafnafs** [comment]
@owwas-nqb, Yes it can be used like this!
You can create a component and put the calendar inside the component and create an html date input when focus it will open the calendar component.

Let me know if you have any questions!
